name: Issue Linker

on:
  pull_request:
    branches:
      - master

jobs:
  issue_linker:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Linker
        uses: gabrielluong/issue-linker@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-regexp: "Issue #(\\d*)"
          section: "### GitHub Automation"
