name: QA Needed

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
    branches:
      - master

jobs:
  qa_needed:
    runs-on: ubuntu-latest
    steps:
      - name: QA Needed
        uses: gabrielluong/qa-needed@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          label: "eng:reopen-for-qa"
          check-regexp: "- \\[([ xX]?)\\] \\*\\*QA Needed\\*\\*"
